spring.application.name=barbeariaSaas
spring.datasource.url=jdbc:mysql://root:ZMJSxByXBHQLzAMRQLbLcKKFeApbLenO@ballast.proxy.rlwy.net:44229/railway
spring.datasource.username=root
spring.datasource.password=ZMJSxByXBHQLzAMRQLbLcKKFeApbLenO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

minha.chave.jwt=eu-era-feliz-antes-de-2006
minha.chave.bot=eu-era-feliz-antes-de-2006